USE VOID_DEV;

CREATE TABLE IF NOT EXISTS SCRIPTS (
	ID INTEGER AUTO_INCREMENT,
    SCRIPT_NAME VARCHAR(50),
    CONSTRAINT PK_SCRIPTS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CONSTANTS (
	CONSTANT_KEY VARCHAR(50),
    CONSTANT_VALUE VARCHAR(100),
    SCRIPT_ID INTEGER,
    CONSTRAINT PK_CONSTANTS PRIMARY KEY (CONSTANT_KEY),
    CONSTRAINT FK_CONSTANTS_SCRIPT_ID FOREIGN KEY (SCRIPT_ID) REFERENCES SCRIPTS (ID)
);

CREATE TABLE IF NOT EXISTS EXECUTION_LOG (
	SCRIPT_ID INTEGER,
    EXECUTION_TIME DATETIME,
	CONSTRAINT FK_EXECUTION_LOG_SCRIPT_ID FOREIGN KEY (SCRIPT_ID) REFERENCES SCRIPTS (ID)
);

CREATE TABLE IF NOT EXISTS QUORA_ACCOUNTS (
	ID INTEGER AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(50),
    QUORA_PASSWORD VARCHAR(20),
    BIRTH_DATE DATE,
    PHONE_NUMBER VARCHAR(15),
    LINK VARCHAR(200),
    CONSTRAINT PK_QUORA_ACCOUNTS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS QUORA_QUESTION_ACCOUNT_DETAILS (
	QUESTION_ID INTEGER,
    QUORA_ACCOUNT_ID INTEGER,
    ASSIGNED BOOLEAN DEFAULT FALSE,
    ANSWERED BOOLEAN DEFAULT FALSE,
    REQUESTED BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_QQAD_QUESTION_ID FOREIGN KEY (QUESTION_ID) REFERENCES QUORA_QUESTIONS(ID),
    CONSTRAINT FK_QQAD_QA_ID FOREIGN KEY (QUORA_ACCOUNT_ID) REFERENCES QUORA_ACCOUNTS(ID),
    CONSTRAINT PK_QQAD PRIMARY KEY (QUESTION_ID, QUORA_ACCOUNT_ID)
);

INSERT INTO SCRIPTS (SCRIPT_NAME) VALUES ('Refresh_Quora_Accounts_Data'), ('Fill_Quora_Question_Dates');

INSERT INTO CONSTANTS VALUES ('class_name', 'Box-sc-9env3-0 gNyDNu', 1), ('class_attr_name', 'div', 1), ('sub_class_1_name', 'q-text qu-color--gray_light qu-fontSize--small qu-passColorToLinks', 1),
('sub_class_1_attr_name', 'div', 1), ('sub_class_2_name', 'Box-sc-9env3-0 eZSsnB', 1), ('sub_class_2_attr_name', 'a', 1), ('date_format', '%B %d, %Y', 1);